### PR TITLE
users can unsubscribe from a thread

### PR DESCRIPTION
**Pull request by jamesnvc**

### CODE REVIEW

**Comment by jamesnvc** [comment]
screen shot 2016-06-15 at 11 37 20

**Comment by jamesnvc** [comment]
Very open to changing the UI

**Comment by rafd** [comment]
Re: UI, here's a thought:
  on hover over the X, more options show up below (or to the side) (with the X in the same spot)
  ...so, clicking on X still is just a click, but doing something extra is: hovering over x, and then nudging to the side?

Also... I think "muting" a conversation should immediately close it too.

**Comment by jamesnvc** [comment]
Muting does currently close it

**Comment by jamesnvc** [comment]
Ah, I see, fixed

**Pull request merged**
