### PR TITLE
Issue: #135 Add a user administration page (for admins only)

### PR DESCRIPTION
**Pull request by GeoDoo**
- [x] Add a menu item in the admin menu
- [x] Ideally menu item should be a hook
- [x] Create a module for the page
- [x] Read users from state
- [x] List of users with name and "make user an admin" button (as first step)
- [ ] The page should list of users in a table (with their name, last-sign in) and buttons to remove user or make the user an admin. 
- [ ] Later, add the ability to bulk invite users.

### CODE REVIEW

**Comment by jamesnvc** [comment]
Looking good! I just pushed a change to master (946fe28e) that makes admin-header-views a hook. You should now be able to remove your change to header.cljs & "register" the header item in the same manner as the `bots` module [now does](https://github.com/braidchat/braid/commit/946fe28e8aa2382d16392343f6b596e7024925c4#diff-70c26d37b185dff4607bb9a3b1aa35e9R31).

**Comment by GeoDoo** [comment]
Cool! Thanks for that! I tried to make the changes you made but I couldn't do it! 😄 

Check now! It should be ok I guess

**Comment by jamesnvc** [comment]
Nice! Btw, one other thing to note: currently, although the link only shows up if the user is an admin, the user can still manually type the url in to get to that page. The `users-page-view` should probably also check if the user viewing is an admin for the current group -- see `braid.bots.client.views.bots-page` for an example of how we do that.

**Comment by jamesnvc** [comment]
Hey @GeoDoo! Just so this PR doesn't bit-rot away, I'm going to clean up some little things and merge it now.

Please feel free to open up a new PR to add more enhancements 😄

**Comment by GeoDoo** [comment]
Cool thanks @jamesnvc sorry for that, busy weeks 😄

**Pull request merged**
