### PR TITLE
Restyle website embeds to make more distinct from conversation flow

### PR DESCRIPTION
**Pull request by sjuraschka**
screen shot 2016-06-03 at 6 18 50 pm

Currently the background color is randomly generated

### CODE REVIEW

**Comment by jamesnvc** [comment]
Merged, but it might be interesting to try to make the colour of the background be constant for a given URL (maybe look into hash functions... :) )

**Comment by sjuraschka** [comment]
Raf said he would teach me that once he figures out how to do that.

**Comment by jamesnvc** [comment]
Well, there's a built-in `hash` function that will give you a number...so something like `(mod (Math/abs (hash "url string")) 360)` should do it

**Comment by jamesnvc** [comment]
or `(->> content :url hash Math/abs (mod 360))` depending on how you'd like to write it :p

**Comment by rafd** [comment]
Just about to issue a PR

**Comment by jamesnvc** [comment]
actually, I think the way I suggested may not work great, colours seem fairly biased towards red

**Comment by jamesnvc** [comment]
ha, never mind, that should just be a single arrow `->` in the above code, not `->>`

**Pull request merged**
