### PR TITLE
Aws credentials provider support

### PR DESCRIPTION
**Pull request by cch1**
This PR provides a late binding for AWS credentials -essential for AWS role-based credentials and STS.

Despite mimicking the AWSCredentialsProvider api, this PR does not add a dependency on the AWS SDK.  At some future time it would probably be a good idea to replace the custom work in `braid.lib.aws` in favor of the SDK approach but I'm not tackling that here.

### CODE REVIEW

**Comment by jamesnvc** [comment]
>  At some future time it would probably be a good idea to replace the custom work in braid.lib.aws in favor of the SDK approach

I believe we specifically removed the AWS SDK previously. I don't like pulling in a dependency that large just to wrap some HTTP API calls.

**Comment by jamesnvc** [comment]
I generally like to have whitespace-only changes in their own commits, but I'm okay if that's a pain to separate them out.

**Comment by cch1** [comment]
Understood and agreed.  Unfortunately those changes are made automatically by `clojure-mode` in emacs which tries to adhere to the [style guide](https://guide.clojure.style/).  I appreciate your flexibility in accepting this PR with those changes embedded within.

**Comment by cch1** [comment]
> > At some future time it would probably be a good idea to replace the custom work in braid.lib.aws in favor of the SDK approach
> 
> I believe we specifically removed the AWS SDK previously. I don't like pulling in a dependency that large just to wrap some HTTP API calls.

That was my assumption.  Worth mentioning that the new SDK has documented support for pulling in subsets of the entire sdk....

**Pull request merged**
