### PR TITLE
Upload by group

### PR DESCRIPTION
**Pull request by jamesnvc**
Organize uploaded files by group & have the ability to see said files

To come later: Search/filter uploaded files, see them in context

### CODE REVIEW

**Comment by rafd** [comment]
We should probably have files as objects in the database, not just "links in messages"

**Comment by jamesnvc** [comment]
That would probably make more sense...I'll discard this branch and try that approach

**Comment by rafd** [comment]
Or... defer until later? Your call. 

Having files as first-class objects will make things a lot more flexible later.

**Comment by jamesnvc** [comment]
Yeah, it definitely makes more sense...the next thing I wanted to do was make it so you could see the thread the file was posted in, but that'd be kind if ugly right now. I'll think about it

**Pull request closed without merging**
