### PR TITLE
Show changelog in client

### PR DESCRIPTION
**Pull request by jamesnvc**

### CODE REVIEW

**Comment by jamesnvc** [comment]
In a slightly awkward situation with the generated changelog.cljs --- I want to have an empty version of the file in git, so that the cljs compiles cleanly even without running the generate script, but having the file tracked, means the gitignore is no longer relevant.  There's a repository-local way to ignore changes to the file (`git update-index --assume-unchanged <file>`), but if someone else pulls, they don't get that, and if they run the generate script, git will show the file as modified.

Maybe just keep it as-is and assume people are okay with an empty changelog in dev?

**Comment by rafd** [comment]
Perhaps have a server route that reads `changelog.md`, and front-end gets it via an API vs. injecting a cljs file?

**Comment by jamesnvc** [comment]
Yeah, I'm thinking that that is probably the way to go...I originally was going to do that way, then figures that since its set at build time, may as well do this...but now I'm thinking that as changelog grows, it'll just bloat the js the client has to load, for the sake of having a faster load time for that page but that's not really worth it, as that is a fairly rare occurrence.

**Comment by jamesnvc** [comment]
Changed so the client fetches the changelog hiccup over ajax instead of having it built statically

**Comment by jamesnvc** [comment]
It is currently parsing the markdown into hiccup server-side; I'm considering using the cljs port of instaparse, but it's been too slow to be usable in the past and given how rarely people are likely to hit it, I don't imagine the extra server load should be an issue.

**Comment by jamesnvc** [comment]
Running a dumb little benchmark, it takes a little under four seconds to parse a 400-line changelog in clj, which would probably mean at least 30 seconds to do in cljs

**Pull request merged**
