### PR TITLE
Prevent thread jumping [in-progress]

### PR DESCRIPTION
**Pull request by rafd**
This PR addresses the issue of threads jumping around in the inbox. https://github.com/braidchat/meta/issues/255

The solution is a modification to `threads-view`, converting it to a Form-3 reagent component with some `component-will-receive-props` logic instead of blindly rendering whatever threads were given to the component.

Essentially, when new props are incoming, the component identifies which threads are the same as before, which are new, and which are to be deleted. Then, it:
 1. takes the original vector of threads 
 2. removes the threads that are no longer necessary (this moves threads, but does not reorder, --- since it  can only be initiated by user input, its ok)
 3. *appends* the new threads to the list (which guarantees that existing threads don't move)

When the page is changed, or the app refreshed, the order of threads will likely not be identical to the order prior-to-change/refresh (because all threads are "new" and will follow the set sorting order without restriction). This doesn't seem to be much of an issue.

TO DO:
- [x] Bring back scroll 
- [x] Bring back focus-chan on new-message view;  @jamesnvc what was this for?

### CODE REVIEW

**Comment by jamesnvc** [comment]
focus-chan is so when you click on a thread, it focuses the reply text field

**Comment by rafd** [comment]
Works now.

Refactored to make `focused-thread-id` part of state, and removed use of async channels, added a `focus-thread` dispatcher (which will make implementing this with keyboard shortcuts easier).

Aside: with reagent/reframe, there seem to be less reason to use clojure.async channels than with om.

**Comment by rafd** [comment]
Just noticed an issue: when creating a new thread, the old thread remains focused. Investigating.

**Comment by rafd** [comment]
Fixed. Should be ready to go now. Give it a try.

**Comment by jamesnvc** [comment]
Seems good to me, although I'm not sure why clicking on, e.g. the add button, works now; from looking at the code, it seems like it should have the problem where clicking causes the thread to focus & stopping the input from opening?

Also, it seems like new messages I send aren't marked as read - is that by design?

**Comment by rafd** [comment]
> Seems good to me, although I'm not sure why clicking on, e.g. the add button, works now; from looking at the code, it seems like it should have the problem where clicking causes the thread to focus & stopping the input from opening?

Previously, there were both `on-click` and `on-focus` handlers on the thread, but only `on-click` is necessary (it avoids the text-highlighting issue). `on-focus` was then added to the textarea, so it gets triggered when tabbing between textareas.

> Also, it seems like new messages I send aren't marked as read - is that by design?

Nope. A regression. I will look into it now.

**Comment by rafd** [comment]
Fixed. The new way of adding/removing threads (to prevent thread jumping) resulted in certain views not being re-rendered which used to before. Added a subscription to message-views to fix the issue.

**Comment by jamesnvc** [comment]
Conflicts now; wanna fix 'em & merge?

**Comment by rafd** [comment]
Addresses https://github.com/braidchat/meta/issues/255

**Pull request merged**
