### PR TITLE
indicate sub status of tags in autocomplete

### PR DESCRIPTION
**Pull request by jamesnvc**

### CODE REVIEW

**Comment by jamesnvc** [comment]
screenshot-2016-07-09_21 45 01_edt-04 00_1468115101

**Comment by jamesnvc** [comment]
Addresses https://github.com/braidchat/meta/issues/328

**Comment by rafd** [comment]
Nice, can you maybe throw in the tag description as well? (second line, there should be styles available for it already)

**Comment by jamesnvc** [comment]
I think it is there, those tags just don't have one set

**Comment by jamesnvc** [comment]
screenshot-2016-07-10_16 06 48_edt-04 00_1468181208

**Comment by jamesnvc** [comment]
er, that should be 
screenshot-2016-07-10_17 24 29_edt-04 00_1468185869, not sure why that was appearing filled in

**Pull request merged**
